server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://test.c0xvfvhlcqd9.ap-northeast-2.rds.amazonaws.com:3306/gomoku
    username: ENC(P6wCfe/ci58/KS2Bd+9ulczXTXno+OdXl0tsJ6ZQr4v3/GVm9ECIpJR+e38Ein1X)
    password: ENC(jNt1VDpiz8If7Lz2IKxWqrE6QXNvsCq8mEcFZnYOOkn/EZ1Ns80DVG2Og1Qy/+C1)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


jwt:
  secretKey:
    ENC(JwjBqLasnvgojaxfKX+qwIrH8GtzDY21Ueo8g/l7rZ0YpISu/kykz2uSdYBh/1NLNvng62WRLAEC6op+GsBINWKVOajiaPC2jIjsVwLLC5P56McYx4JPwHS6T0FeTzg1)
  accessExpiration: 1800000 #30분 1800000
  refreshExpiration: 604800000 #1주 604800000

jasypt:
  encryptor:
    bean: jasyptEncryptorAES