server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://test.c0xvfvhlcqd9.ap-northeast-2.rds.amazonaws.com:3306
    username: ENC(Y5WQnW/9QvoSM1YyDgHn6gz0X/I16yPDCAw71ukSWnkhrGAQSUCrXZANVFshlOKv)
    password: ENC(Fq7/78A9WJnBhCCQQdADY2eTTPOwU2J8euXg5P3NOQwNZFfXUXV89A3DNFK6v9xA)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update


jwt:
  secretKey:
    ENC(UNPezTos9J3xXq8EmXbwNIcu5WHSczEGsPb7m4vR3Ps7r3UVWkDMzXVLiX7mh7jdQwlUTlfANQUo0CI9Mubk3h1YQfkwhawDsDcur)
  accessExpiration: 1800000 #30분 1800000
  refreshExpiration: 604800000 #1주 604800000

jasypt:
  encryptor:
    bean: jasyptEncryptorAES